# Generated by Django 5.1.1 on 2024-12-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Constellation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("short", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="CelestialBody",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "constellation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="celestial_bodies",
                        to="astronomy.constellation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("distance_au", models.FloatField()),
                ("distance_km", models.FloatField()),
                ("altitude_degrees", models.FloatField()),
                ("azimuth_degrees", models.FloatField()),
                ("right_ascension_hours", models.FloatField()),
                ("declination_degrees", models.FloatField()),
                ("magnitude", models.FloatField()),
                ("elongation", models.FloatField(blank=True, null=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="astronomy.celestialbody",
                    ),
                ),
            ],
        ),
    ]
